[tool.poetry]
name = "gltf-combiner"
version = "0.1.4"
description = ""
authors = ["Danila <crowo4ka@gmail.com>"]
readme = "README.md"
packages = [{include = "gltf_combiner"}]

[tool.poetry.dependencies]
python = "^3.11"
orjson = "3.10.5"
flatbuffers = "^24.3.25"
numpy = "^2.0.0"


[tool.poetry.group.dev.dependencies]
black = "24.4.2"
ruff = "0.5.0"
pyright = "1.1.369"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
